# Naive Bayes Classification of Tweets About the Midterm Election

In [6]:
import csv
import os,re,csv
from nltk.tokenize import RegexpTokenizer
from stop_words import get_stop_words
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from gensim import corpora, models
import gensim
import numpy as np
import scipy
import math
import matplotlib.pyplot as plt
import plotly.plotly as py
import twitter
import json

In [7]:
# Set up input and output variables for the script
midtermtweets = open("data.csv", "r")
 
# Set up CSV reader and process the header
csvReader = csv.reader(midtermtweets)

# Get tweet text and sentiment
tweettext = []
sentiment = []
# Loop through the lines in the file and get each coordinate
for row in csvReader:
    text = row[1]
    affect = row[0]
    tweettext.append(text)
    sentiment.append(affect)
 
# Print the coordinate list
print(sentiment)

midtermtweets.close()

['sentiment', 'negative', 'negative', 'negative', 'neutral', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'neutral', 'negative', 'positive', 'negative', 'neutral', 'negative', 'positive', 'negative', 'negative', 'negative', 'neutral', 'neutral', 'positive', 'neutral', 'negative', 'positive', 'positive', 'positive', 'positive', 'negative', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'neutral', 'negative', 'negative', 'neutral', 'positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'neutral', 'negative', 'neutral', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'negative', 'neutral', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'neutral', 'negative', 'neutral', 'negative', 'negative', 'negative', 'ne

Here we enter our Twitter credentials. These can be acquired through 

## 1. Pre-processing

In [17]:
tweettext[1]

'RT @nytimes: The New York Times needs your help. We’re looking for false information being spread deliberately to confuse, mislead, or infl…'

In [12]:
from textblob import TextBlob
import re

def clean_tweet(tweet):
    '''
    Utility function to clean the text in a tweet by removing 
    links and special characters using regex.
    '''
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())


cleantweets =[clean_tweet(tweet) for tweet in tweettext]

cleantweets = cleantweets[1:] # Need to get rid of the headers

cleantweets[0]

'RT The New York Times needs your help We re looking for false information being spread deliberately to confuse mislead or infl'

In [18]:
# Vectorized
# Divide into training and test
# Training

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_counts = count_vect.fit_transform(cleantweets)
X_counts.shape
Labels = sentiment[1:]

X_train = X_counts[0:60]
Y_train = Labels[0:60]

X_test = X_counts[60:]
Y_test = Labels[60:]

# Instructions:
1. Train a multinomial Naive Bayes Classifier.
2. Report Precision, Recall and F1 Statistics

In [30]:
from sklearn import naive_bayes
clf = naive_bayes.MultinomialNB()
clf.fit(X_train, Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [43]:
from sklearn.metrics import f1_score

f1_score(Y_train, clf.predict(X_train), labels=['positive','negative','neutral'], average='weighted')

1.0

In [44]:
f1_score(Y_test, clf.predict(X_test), labels=['positive','negative','neutral'], average='weighted')

0.7631802979629067

In [45]:
f1_score(Y_test, clf.predict(X_test), labels=['positive','negative','neutral'], average='micro')

0.75

In [46]:
f1_score(Y_test, clf.predict(X_test), labels=['positive','negative','neutral'], average='macro')

0.6597750076010945

In [50]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(Y_test, clf.predict(X_test), labels=['positive','negative','neutral'])

(array([0.5, 1. , 0.5]),
 array([0.77777778, 0.83333333, 0.42857143]),
 array([0.60869565, 0.90909091, 0.46153846]),
 array([ 9, 24,  7]))

In [56]:
import pandas as pd
y = pd.Series(Y_test)

In [60]:
len(y[y == "negative"])

24

In [61]:
len(y[y == "positive"])

9

In [63]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, clf.predict(X_test)))

             precision    recall  f1-score   support

   negative       1.00      0.83      0.91        24
    neutral       0.50      0.43      0.46         7
   positive       0.50      0.78      0.61         9

avg / total       0.80      0.75      0.76        40



In [64]:
(24/40)*.91 + (7/40)*.46 + (9/40)*.61

0.76375

In [65]:
f1_score(Y_test, clf.predict(X_test), labels=['positive','negative','neutral'], average='weighted')

0.7631802979629067